gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_NormalHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Normal Type TMs!\p"
	.string "How may I serve you?$"

gText_FireHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Fire Type TMs!\p"
	.string "How may I serve you?$"

gText_WaterHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Water Type TMs!\p"
	.string "How may I serve you?$"

gText_GrassHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Grass Type TMs!\p"
	.string "How may I serve you?$"

gText_ElectricHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Electric Type TMs!\p"
	.string "How may I serve you?$"

gText_IceHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Ice Type TMs!\p"
	.string "How may I serve you?$"

gText_FightingHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Fighting Type TMs!\p"
	.string "How may I serve you?$"

gText_PoisonHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Poison Type TMs!\p"
	.string "How may I serve you?$"

gText_GroundHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Ground Type TMs!\p"
	.string "How may I serve you?$"

gText_FlyingHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Flying Type TMs!\p"
	.string "How may I serve you?$"

gText_PsychicHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Psychic Type TMs!\p"
	.string "How may I serve you?$"

gText_BugHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Bug Type TMs!\p"
	.string "How may I serve you?$"

gText_RockHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Rock Type TMs!\p"
	.string "How may I serve you?$"

gText_GhostHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Ghost Type TMs!\p"
	.string "How may I serve you?$"

gText_DragonHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Dragon Type TMs!\p"
	.string "How may I serve you?$"

gText_DarkHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Dark Type TMs!\p"
	.string "How may I serve you?$"

gText_SteelHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Steel Type TMs!\p"
	.string "How may I serve you?$"

gText_FairyHowMayIServeYou::
	.string "Welcome!\n"
	.string "I sell Fairy Type TMs!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"
